- hosts: localhost
  any_errors_fatal: true
  vars:
    uds_meta_storage_class: rook-ceph-block
    uds_storage_class: rook-cephfs
    mas_instance_id: masinst1
    mas_config_dir: ~/masconfig
    uds_contact:
      email: "jan.kowalski@pl.ibm.com"
      first_name: "jan"
      last_name: "kowalski"
  roles:
  - ibm.mas_devops.uds_install
